### ISSUE TITLE
In case of an invalid _default_action

### ISSUE THREAD

**Issue by polyvertex** [ueffel/Keypirinha-Plugin-Kill#1]
There's a potential bug at [line 192](https://github.com/ueffel/Keypirinha-Plugin-Kill/blob/master/Kill.py#L192) in case `self._default_action` is not found in `self._actions`. You probably want to correct that at [line 33](https://github.com/ueffel/Keypirinha-Plugin-Kill/blob/master/Kill.py#L33) in `_read_config`. For that matter, to call `settings.get_enum` should be more appropriate in your case.

**Comment by ueffel** [comment]
Thanks for reporting that. I see what you mean, i cant be sure what a user would put in the config and if it is one of my valid actions.
