### ISSUE TITLE
Can this plugin have an option to ignore the background processes?

### ISSUE THREAD

**Issue by Just1n** [ueffel/Keypirinha-Plugin-Kill#11]
same as the title?

**Comment by ueffel** [comment]
How would you distinguish background processes from a foreground process?

What I think could be the classification a foreground process:
* Every process that has a visible window? (essentially what the taskswitcher package from keypirinha shows, just the corresponding processes) OR
* Every process that has a window (visible or not)? That includes processes that only have a tray icon (they typically have a hidden window) OR
* maybe something entirely else?

What do you think?

Also: I think of this package like a searchable taskmanager, what is your use case?

**Comment by Just1n** [comment]
Let's see the Task Manager of Windows:
These are  foreground processes:
![image](https://user-images.githubusercontent.com/517376/31009298-88b028cc-a539-11e7-87e6-ee9bbf4cab0a.png)

These are background processes:
![image](https://user-images.githubusercontent.com/517376/31009353-aa1f9a92-a539-11e7-9447-799c8ff6b6de.png)

The annoyance of using kill plugin is that, for example, whenever I type "chrome", it will list all the chrome processes (both foreground & background), without the name of the processes, too many listed processes make me hard to determine which process is the one that I want to kill.

I don't have any experience on coding with the processes using python. But I think since [Task Manager] can distinguish background processes from a foreground process, then we can.

**Comment by polyvertex** [comment]
@ueffel in addition to your bullet points, perhaps a thing to consider is checking on process' parent. For instance a process that has `explorer.exe` as a parent is more likely to be a candidate than a child process of `chrome.exe`

**Comment by polyvertex** [comment]
Mmmh yeah no. Bad idea. KP's child processes for example are top apps usually for example. Wrote too soon :)
