### ISSUE TITLE
Looks like 'hide_background' doesn't work as it's expected

### ISSUE THREAD

**Issue by Just1n** [ueffel/Keypirinha-Plugin-Kill#13]
I have set hide_background = yes

See my task manager:
![image](https://user-images.githubusercontent.com/517376/33305912-0edc93d2-d44b-11e7-866a-98396f8898ef.png)

When I use this plugin:
![image](https://user-images.githubusercontent.com/517376/33305953-446a8d56-d44b-11e7-9d38-d6edf60f3d75.png)

But I can see it in TaskSwitcher plugin:
![image](https://user-images.githubusercontent.com/517376/33306131-13fca48c-d44c-11e7-83b1-2235ca9127d3.png)

Perhaps we can reuse the logic of getting available processes in TaskSwitcher plugin?

**Comment by ueffel** [comment]
The logic of the TaskSwitcher plugin is reused. I guess the executable for your application does not have "car" in it. The application you are looking for is probably in there under a different name. Can you check in the task manager whats the executable's name (right click > Go to details) and look if you can find it with that name in the kill list?

Maybe it would be better to have the window title as caption for the items, so that they're also searchable.

**Comment by Just1n** [comment]
I have tried it.
The name in Details tab is almost same with it is in Processes tab.

The problem is, the specific process is resulted in TaskSwitcher list but not in Kill list, with the same key words.
How could this happen if the 2 plugins use same code to find the processes?

**Comment by ueffel** [comment]
The Taskswitcher lists the window title, the Kill Package lists the executable name.
So for example: 
Microsoft Visual Studio

The Taskswitcher would list it as "Projectname - Microsoft Visual Studio"
Kill Package would list it as "devenv.exe"

**Comment by Just1n** [comment]
Well, forgot to tell you, the expected process listed as background if I set hide_background = no, but actually it's foreground.
![image](https://user-images.githubusercontent.com/517376/33314039-61dbac0a-d467-11e7-9a5e-dd677abbdd8f.png)

**Comment by ueffel** [comment]
Didn't refresh the window list -.-
Do you find your application if you restart keypirinha? (At least the first time you use the kill command.)

Can you try this version and see if it works as expected?
[Kill.zip](https://github.com/ueffel/Keypirinha-Plugin-Kill/files/1509422/Kill.zip)
Rename it to Kill.keypirinha-package and drop it in InstalledPackages

Changes:
* refresh window list
* label of the items includes the window title

**Comment by Just1n** [comment]
Hey @ueffel , great! New Kill.zip works as expected.
That's the cause - didn't refresh the window list.

Have you submitted it to Github repository?

**Comment by ueffel** [comment]
I'll make a Release out of it later today
