### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by s-oram** [ueffel/Keypirinha-Plugin-Kill#14]
How is the Kill plugin installed? 

The readme says refer to the "release notes" but I can't see any release notes in the repository. 

Thanks

**Comment by ueffel** [comment]
Sorry for the late response.

The release notes are located in the release section underneath downloadable files.
https://github.com/ueffel/Keypirinha-Plugin-Kill/releases

Maybe I should link it in the readme.

**Comment by ueffel** [comment]
Fixed in 74a26eb

**Comment by s-oram** [comment]
Thanks Ueffel :)
