### ISSUE TITLE
Kill all processes that matches the query

### ISSUE THREAD

**Issue by bielej** [ueffel/Keypirinha-Plugin-Kill#16]
Hi
This is more a feature request than an issue, but could you add a possibility to kill multiple processes at once? For example Chrome has multiple processes and killing them one at a time is a pain. 
Killy for Launchy had this feature and I really miss it after migrating to Keypiranha.

Cheers

**Comment by bielej** [comment]
Never mind, I've read the config file ;)

**Comment by ueffel** [comment]
You don't have to change the default action, you can also make a one-time choice to kill by name with the actions. Just search for a process and then press tab to see the actions.
