### ISSUE TITLE
is it possible to "prefer" Foreground Apps but dont hide Background Apps

### ISSUE THREAD

**Issue by killtux** [ueffel/Keypirinha-Plugin-Kill#17]
i'd like to show background apps, but most time i want to kill the foreground. so if its possible to set priority to foreground you dont have to tap the curser down so many times.

would be nice to get implemented

**Comment by ueffel** [comment]
The sorting of the result list uses keypirinha's default scoring algorithm. Sadly it's impossible to hook into that and change the score of specific items. I would have to reimplement the scoring algorithm, which is not feasible.
I could implement that the list without search terms is sorted by foreground/background and then by window title/process name. But as soon as search terms are entered the result list would still be sorted by score.

I have a suggestion for you: Every item has either "(foreground)" or "(background)" at the end. So if you just type "fore" at the end of your search term, you only see the foreground items you seek.
