### ISSUE TITLE
load_icon call

### ISSUE THREAD

**Issue by polyvertex** [ueffel/Keypirinha-Plugin-Kill#6]
Hi, I've just noticed that you [directly call the load_icon function](https://github.com/ueffel/Keypirinha-Plugin-Kill/blob/master/kill.py#L114) of the `keypirinha` module instead of calling the [keypirinha.Plugin.load_icon](http://keypirinha.com/api/plugin.html?highlight=package_full_name#keypirinha.Plugin.load_icon) method (i.e. `self.load_icon`), which would be safer.

**Comment by ueffel** [comment]
Fixed in 2.3
