### ISSUE TITLE
War and peace

### ISSUE THREAD

**Issue by sergeevabc** [ueffel/Keypirinha-Plugin-Kill#7]
Dear Steffen,

It seems the way you and I exchanged opinions last night on Gitter was misinterpreted by @polyvertex.
He believes I owe you an apology (despite no harm was meant) and because of that ban was set.
Could you be so kind to assure him no harm was done to you so we could resolve this misunderstanding?

P. S. Thank you for this plugin as well, works flawlessly.

**Comment by ueffel** [comment]
Why would you open an issue on this repository because of this? It has nothing at all to do with the plugin. You could have messaged me via Gitter privately or something.
